-- INSERT INTO core.contracts (client_id, contract_code, contract_name, description, start_date, end_date, revenue, status, created_by, lead_by)
-- SELECT 
--   cl.id, 
--   'CTR-2026-FBC01', 
--   'FreshBrew Coffee Monthly Retainer', 
--   'Regular monthly content planning, creation, and production.',
--   CURRENT_DATE - INTERVAL '15 days', 
--   CURRENT_DATE + INTERVAL '15 days', 
--   15000000.00, 
--   'active', 
--   u_owner.id, 
--   u_lead.id
-- FROM core.clients cl
-- JOIN core.users u_owner ON u_owner.email = 'owner@sejajar.id'
-- JOIN core.users u_lead ON u_lead.email = 'contentlead@sejajar.id'
-- WHERE cl.company_name = 'FreshBrew Coffee'
-- ON CONFLICT (contract_code) DO NOTHING;

-- INSERT INTO core.contracts (client_id, contract_code, contract_name, description, start_date, end_date, revenue, status, created_by, lead_by)
-- SELECT 
--   cl.id, 
--   'CTR-2026-FBC02', 
--   'FreshBrew Coffee Promo Ramadan', 
--   'Promo campaign for Ramadan special beverages.',
--   CURRENT_DATE - INTERVAL '25 days', 
--   CURRENT_DATE + INTERVAL '3 days', 
--   8000000.00, 
--   'active', 
--   u_owner.id, 
--   u_lead.id
-- FROM core.clients cl
-- JOIN core.users u_owner ON u_owner.email = 'owner@sejajar.id'
-- JOIN core.users u_lead ON u_lead.email = 'contentlead@sejajar.id'
-- WHERE cl.company_name = 'FreshBrew Coffee'
-- ON CONFLICT (contract_code) DO NOTHING;

-- INSERT INTO core.contracts (client_id, contract_code, contract_name, description, start_date, end_date, revenue, status, created_by, lead_by)
-- SELECT 
--   cl.id, 
--   'CTR-2026-FBC03', 
--   'FreshBrew Coffee Grand Opening Launch', 
--   'Grand opening social media campaign and influencer relations.',
--   CURRENT_DATE - INTERVAL '30 days', 
--   CURRENT_DATE, 
--   25000000.00, 
--   'active', 
--   u_owner.id, 
--   u_lead.id
-- FROM core.clients cl
-- JOIN core.users u_owner ON u_owner.email = 'owner@sejajar.id'
-- JOIN core.users u_lead ON u_lead.email = 'contentlead@sejajar.id'
-- WHERE cl.company_name = 'FreshBrew Coffee'
-- ON CONFLICT (contract_code) DO NOTHING;

-- INSERT INTO core.contracts (client_id, contract_code, contract_name, description, start_date, end_date, revenue, status, created_by, lead_by)
-- SELECT 
--   cl.id, 
--   'CTR-2026-FBC04', 
--   'FreshBrew Coffee New Menu Campaign', 
--   'Campaign for launching and promoting new signature menu items.',
--   CURRENT_DATE - INTERVAL '45 days', 
--   CURRENT_DATE - INTERVAL '5 days', 
--   12000000.00, 
--   'active',
--   u_owner.id, 
--   u_lead.id
-- FROM core.clients cl
-- JOIN core.users u_owner ON u_owner.email = 'owner@sejajar.id'
-- JOIN core.users u_lead ON u_lead.email = 'contentlead@sejajar.id'
-- WHERE cl.company_name = 'FreshBrew Coffee'
-- ON CONFLICT (contract_code) DO NOTHING;

-- INSERT INTO core.contracts_platforms (contract_id, platform_id)
-- SELECT c.id, p.id
-- FROM core.contracts c
-- CROSS JOIN core.platforms p
-- WHERE c.contract_code IN ('CTR-2026-FBC01', 'CTR-2026-FBC02', 'CTR-2026-FBC03', 'CTR-2026-FBC04')
--   AND p.platform_name IN ('Instagram', 'TikTok', 'YouTube')
-- ON CONFLICT DO NOTHING;

-- INSERT INTO core.contract_teams (contract_id, user_id)
-- SELECT c.id, u.id
-- FROM core.contracts c
-- CROSS JOIN core.users u
-- WHERE c.contract_code IN ('CTR-2026-FBC01', 'CTR-2026-FBC02', 'CTR-2026-FBC03', 'CTR-2026-FBC04')
--   AND u.email IN ('editor@sejajar.id', 'writer@sejajar.id')
-- ON CONFLICT DO NOTHING;
